import streamlit as st
import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import RobustScaler

# --- PAGE CONFIG ---
st.set_page_config(page_title="Phishing Detection AI", layout="wide")

@st.cache_resource
def load_and_train_model():
    # 1. Load dataset
    try:
        df = pd.read_csv('StealthPhisher_mini.csv') 
    except FileNotFoundError:
        df = pd.read_csv('StealthPhisher2025.csv')

    # 2. Select ONLY the highly crucial features controlled by the UI
    # Added IsDomainIP to the list
    ui_features = ['ShannonEntropy', 'NumberOfSubdomains', 'IsFormSubmitExternal', 'IsDomainIP']
    
    # Ensure columns exist to prevent crashes
    available_features = [f for f in ui_features if f in df.columns]
    if not available_features:
        raise ValueError("None of the critical features were found in the CSV!")
        
    features_only = df[available_features]
    
    # 3. Scale the data
    scaler = RobustScaler()
    X_scaled = scaler.fit_transform(features_only)

    # 4. Train Isolation Forest
    iso_forest = IsolationForest(contamination=0.15, random_state=42)
    iso_forest.fit(X_scaled)
    
    # 5. Create Baseline for UI Input
    baseline = features_only.iloc[[0]].copy()
    baseline[available_features] = features_only[available_features].median().values
    
    return scaler, iso_forest, baseline, available_features

# Initialize model
try:
    scaler, iso_model, baseline_template, active_features = load_and_train_model()
except Exception as e:
    st.error(f"⚠️ Deployment Error: {e}")
    st.stop()

# --- STREAMLIT UI ---
st.title("🛡️ Phishing Detection: Threat Indicator Analysis")
st.write("Evaluating crucial email threat indicators using an Isolation Forest anomaly detection model.")

st.sidebar.header("Test Email Features")

# Feature 1: Shannon Entropy
entropy = st.sidebar.slider(
    "Shannon Entropy (Gibberish Level)", 
    min_value=0.0, max_value=8.0, value=3.5, step=0.1, 
    help="Higher values indicate random, unreadable URLs often generated by attackers."
)

# Feature 2: Subdomains
subdomains = st.sidebar.number_input(
    "Number of Subdomains", 
    min_value=0, max_value=15, value=0, 
    help="Phishing sites often bury the real domain under many fake ones (e.g., secure.login.paypal.malicious.com)."
)

# Feature 3: External Form
external_form = st.sidebar.radio(
    "Does the page submit forms externally?", 
    options=["No", "Yes"], 
    index=0, 
    help="A massive red flag. Malicious sites host fake logins that secretly send passwords to an external attacker server."
)
ext_form_val = 1 if external_form == "Yes" else 0

# Feature 4: Is Domain IP
domain_ip = st.sidebar.radio(
    "Does the URL use an IP address?", 
    options=["No", "Yes"], 
    index=0, 
    help="Legitimate sites use registered domain names. Raw IP addresses (e.g., 192.168.1.1) in links are highly suspicious."
)
domain_ip_val = 1 if domain_ip == "Yes" else 0


if st.button("Run AI Analysis"):
    # Prepare input
    input_df = baseline_template.copy()
    
    if 'ShannonEntropy' in active_features:
        input_df['ShannonEntropy'] = entropy
    if 'NumberOfSubdomains' in active_features:
        input_df['NumberOfSubdomains'] = subdomains
    if 'IsFormSubmitExternal' in active_features:
        input_df['IsFormSubmitExternal'] = ext_form_val
    if 'IsDomainIP' in active_features:
        input_df['IsDomainIP'] = domain_ip_val
    
    # Scale and Predict
    input_scaled = scaler.transform(input_df)
    iso_res = iso_model.predict(input_scaled)[0]
    
    st.divider()
    
    # Show Results
    if iso_res == 1:
        st.success("### Final Verdict: ✅ LEGITIMATE")
        st.write("The model considers these feature parameters to be within normal, safe bounds.")
    else:
        st.error("### Final Verdict: 🚨 PHISHING (Anomaly Detected)")
        st.write("High confidence phishing attempt! The combination of these specific threat indicators triggered the anomaly detector.")